import { SearchSuggestion } from './search.models';

/** A small local index mirroring the most visible source search results. */
export const SEARCH_SUGGESTIONS: SearchSuggestion[] = [
  { title: 'Foundations', category: 'Foundations', href: '/foundations' },
  { title: 'Foundations overview', category: 'Foundations', href: '/foundations' },
  { title: 'Accessibility', category: 'Foundations', href: '/foundations' },
  { title: 'Writing and text', category: 'Foundations', href: '/foundations/writing' },
  { title: 'Building for all', category: 'Foundations', href: '/foundations/building-for-all' },
  { title: 'Develop', category: 'Develop', href: '/develop' },
  { title: 'Develop overview', category: 'Develop', href: '/develop' },
  { title: 'Android', category: 'Develop', href: '/develop/android' },
  { title: 'Android Views', category: 'Develop', href: '/develop/android/mdc-android' },
  { title: 'App bars', category: 'Components', href: '/components/app-bars' },
  { title: 'Badges', category: 'Components', href: '/components/badges' },
  { title: 'Global writing', category: 'Foundations', href: '/foundations/content-design/global-writing' },
  { title: 'Breakpoints', category: 'Foundations', href: '/foundations/layout/breakpoints' },
  { title: 'Bidirectionality & RTL', category: 'Foundations', href: '/foundations/layout/bidirectionality-rtl' },
  { title: 'Usability', category: 'Foundations', href: '/foundations/usability' },
  { title: 'Web', category: 'Develop', href: '/develop/web' },
  { title: 'Extended FABs', category: 'Components', href: '/components/extended-fab' },
  { title: 'Checkbox', category: 'Components', href: '/components/checkbox' },
  { title: 'Text fields', category: 'Components', href: '/components/text-fields' },
  { title: 'Alt text', category: 'Foundations', href: '/foundations/content-design/alt-text' },
  { title: 'XR', category: 'Foundations', href: '/' },
  { title: 'Canonical examples', category: 'Foundations', href: '/foundations/layout/canonical-examples' },
  { title: 'Styles', category: 'Styles', href: '/styles' },
  { title: 'Styles overview', category: 'Styles', href: '/styles' },
  { title: 'Components', category: 'Components', href: '/components' },
  { title: 'Components overview', category: 'Components', href: '/components' },
  { title: 'Jetpack Compose', category: 'Develop', href: '/develop/android/jetpack-compose' },
  { title: 'Buttons', category: 'Components', href: '/components' },
  { title: 'All buttons', category: 'Components', href: '/components/all-buttons' },
  { title: 'Button groups', category: 'Components', href: '/components/button-groups' },
  { title: 'Buttons', category: 'Components', href: '/components/buttons' },
  { title: 'Icon buttons', category: 'Components', href: '/components/icon-buttons' },
  { title: 'Segmented buttons', category: 'Components', href: '/components/segmented-buttons' },
  { title: 'Split button', category: 'Components', href: '/components/split-button' },
  { title: 'Radio button', category: 'Components', href: '/components/radio-button' },
  { title: 'Customizing Material', category: 'Foundations', href: '/foundations/customization' },
  { title: 'Designing', category: 'Foundations', href: '/foundations/designing' },
  { title: 'Content design', category: 'Foundations', href: '/foundations/content-design' },
  { title: 'Design tokens', category: 'Foundations', href: '/foundations/design-tokens' },
  { title: 'Material A-Z', category: 'Foundations', href: '/foundations/glossary' },
  { title: 'FAB menu', category: 'Components', href: '/components/fab-menu' },
  { title: 'FABs', category: 'Components', href: '/components/floating-action-button' },
  { title: 'Notifications', category: 'Foundations', href: '/foundations/content-design/notifications' },
  { title: 'Scaffold', category: 'Foundations', href: '/foundations/layout/scaffold' },
  { title: 'Flutter', category: 'Develop', href: '/develop/flutter' },
  { title: 'Motion', category: 'Styles', href: '/styles/motion' },
  { title: 'Motion physics system', category: 'Styles', href: '/styles/motion/overview' },
  { title: 'Color', category: 'Styles', href: '/styles/color' },
  { title: 'Color system', category: 'Styles', href: '/styles/color/system' },
  { title: 'Color roles', category: 'Styles', href: '/styles/color/roles' },
  { title: 'Color schemes', category: 'Styles', href: '/' },
  { title: 'Color resources', category: 'Styles', href: '/styles/color/resources' },
  { title: 'Style guide', category: 'Foundations', href: '/foundations/content-design/style-guide' },
];
